# Generated by Django 5.0.4 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('done', 'Done'), ('processing', 'Processing')], default='processing', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('orders', models.ManyToManyField(blank=True, related_name='exchange_settlements', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
