# Generated by Django 5.0.4 on 2024-04-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=8)),
            ],
        ),
    ]
